// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Image2;
void ui_event_Switch2( lv_event_t * e);
lv_obj_t *ui_Switch2;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset__3_inch_off[1] = {&ui_img_4_3_inch_off_png};
const lv_img_dsc_t *ui_imgset__3_inch_logo[1] = {&ui_img_4_3_inch_logo_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Switch2( lv_event_t * e) {
  lv_event_code_t event_code = lv_event_get_code(e); lv_obj_t * target = lv_event_get_target(e);
  if ( event_code == LV_EVENT_CLICKED) {
    _ui_checked_set_text_value( ui_Label1, target, "ON", "OFF");
    led_flag_Lock = 1;
    led_flag = !led_flag;
  }
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Image1 = lv_img_create(ui_Screen1);
  lv_img_set_src(ui_Image1, &ui_img_4_3_inch_off_png);
  lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 50
  lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 75
  lv_obj_set_x( ui_Image1, 0 );
  lv_obj_set_y( ui_Image1, -14 );
  lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
  lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
  lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Image2 = lv_img_create(ui_Screen1);
  lv_img_set_src(ui_Image2, &ui_img_4_3_inch_logo_png);
  lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 250
  lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 52
  lv_obj_set_x( ui_Image2, 2 );
  lv_obj_set_y( ui_Image2, -82 );
  lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
  lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
  lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Switch2 = lv_switch_create(ui_Screen1);
  lv_obj_set_width( ui_Switch2, 50);
  lv_obj_set_height( ui_Switch2, 25);
  lv_obj_set_x( ui_Switch2, 2 );
  lv_obj_set_y( ui_Switch2, 42 );
  lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );

  ui_Panel2 = lv_obj_create(ui_Screen1);
  lv_obj_set_width( ui_Panel2, 100);
  lv_obj_set_height( ui_Panel2, 30);
  lv_obj_set_x( ui_Panel2, 3 );
  lv_obj_set_y( ui_Panel2, 95 );
  lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
  lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Label1 = lv_label_create(ui_Panel2);
  lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_x( ui_Label1, 22 );
  lv_obj_set_y( ui_Label1, 1 );
  lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
  lv_label_set_text(ui_Label1, "OFF");

  ui_Label2 = lv_label_create(ui_Panel2);
  lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_x( ui_Label2, -16 );
  lv_obj_set_y( ui_Label2, 1 );
  lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
  lv_label_set_text(ui_Label2, "State:  ");

  lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);

}

void ui_init( void )
{
  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_Screen1_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr( ui_Screen1);
}
