// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
void ui_event_Switch2( lv_event_t * e);
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui____initial_actions0;
extern int led_flag_Lock;
extern int led_flag;

LV_IMG_DECLARE( ui_img_4_3_inch_off_png);   // assets\4.3_inch_off.png
LV_IMG_DECLARE( ui_img_4_3_inch_logo_png);   // assets\4.3_inch_logo.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
