// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: esp32-2.4

#ifndef _UI_COMP_BUTTON2_H
#define _UI_COMP_BUTTON2_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button2
#define UI_COMP_BUTTON2_BUTTON2 0
#define _UI_COMP_BUTTON2_NUM 1
lv_obj_t * ui_Button2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
